// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzU1WG_afAoWG7LOSe_a_QtgE_CtoUcIU',
    appId: '1:399167051437:web:2e770027262e47f887d824',
    messagingSenderId: '399167051437',
    projectId: 'user-project-c4dfc',
    authDomain: 'user-project-c4dfc.firebaseapp.com',
    storageBucket: 'user-project-c4dfc.appspot.com',
    measurementId: 'G-WRG0X35FQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2P5MJQe_Z9M3DDdOQ7MuR6yfaXOr0bF8',
    appId: '1:399167051437:android:ab013644d145cb6e87d824',
    messagingSenderId: '399167051437',
    projectId: 'user-project-c4dfc',
    storageBucket: 'user-project-c4dfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfN-XWrIdGDi_duz6SUqkJvNlKZte3wJM',
    appId: '1:399167051437:ios:0968ea0f479fe12787d824',
    messagingSenderId: '399167051437',
    projectId: 'user-project-c4dfc',
    storageBucket: 'user-project-c4dfc.appspot.com',
    iosBundleId: 'com.example.secondProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfN-XWrIdGDi_duz6SUqkJvNlKZte3wJM',
    appId: '1:399167051437:ios:b7c5ad6ff76a0b6c87d824',
    messagingSenderId: '399167051437',
    projectId: 'user-project-c4dfc',
    storageBucket: 'user-project-c4dfc.appspot.com',
    iosBundleId: 'com.example.secondProject.RunnerTests',
  );
}
